version: "3.8"

services:
  file-server-db:
    image: postgres:16.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: files_db—á